name: Web CI

on:
  push:
    paths:
      - "apps/web/**"
      - "packages/**"
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
